refactor(sdk): convert classes to Kotlin
CAU-Kiel-Tech-Inf/backend pull request #341
Opened 2020-11-30 17:13 UTC by anarchuser

2020-12-01 10:01 UTC, xerus2000 requested changes

2020-12-01 10:01 UTC, xerus2000 commented on sdk/src/framework/sc/shared/WinCondition.kt
> + * Erzeugt eine neue Condition mit Sieger und Gewinngrund.
Was soll eine "Condition" sein?

2020-12-01 10:04 UTC, anarchuser commented on sdk/src/framework/sc/shared/ScoreValue.kt
> +data class ScoreValue(val fragment: ScoreFragment, var value: BigDecimal)
it had a setter before, though

2020-12-01 10:13 UTC, anarchuser commented on sdk/src/framework/sc/shared/WinCondition.kt
> + * Erzeugt eine neue Condition mit Sieger und Gewinngrund.
Keine Ahnung.
ist es mit 910e6c9 besser?

2020-12-01 16:20 UTC, xerus2000 commented on sdk/src/framework/sc/shared/ScoreValue.kt
> +data class ScoreValue(val fragment: ScoreFragment, var value: BigDecimal)
yes, but we don't need to keep dirty architecture ;)

2020-12-01 16:20 UTC, xerus2000 commented on sdk/src/framework/sc/shared/WinCondition.kt
> + * Erzeugt eine neue Condition mit Sieger und Gewinngrund.
ja :)

2020-12-01 16:23 UTC, anarchuser commented on sdk/src/framework/sc/shared/ScoreValue.kt
> +data class ScoreValue(val fragment: ScoreFragment, var value: BigDecimal)
I can see that, but then this whole thing isn't a refactor anymore

2020-12-01 16:24 UTC, anarchuser commented on sdk/src/framework/sc/shared/ScoreValue.kt
> +data class ScoreValue(val fragment: ScoreFragment, var value: BigDecimal)
cb8d600

2020-12-01 16:37 UTC, anarchuser commented on sdk/src/framework/sc/shared/ScoreValue.kt
> +data class ScoreValue(val fragment: ScoreFragment, var value: BigDecimal)
Actually, the GameRoomManager uses the setter.
So unless someone refactors this usage out, ScoreValue.value has to stay mutable

2020-12-02 20:05 UTC, xerus2000 commented on sdk/src/framework/sc/shared/ScoreValue.kt
> +data class ScoreValue(val fragment: ScoreFragment, var value: BigDecimal)
yikes, I feel like I fixed that already somewhere else...

2020-12-02 20:07 UTC, xerus2000 requested changes

2020-12-02 20:07 UTC, xerus2000 commented on sdk/src/framework/sc/shared/ScoreFragment.kt
> +        val name: String?,
i don't think this should be nullable

2020-12-02 20:07 UTC, xerus2000 commented on sdk/src/framework/sc/shared/ScoreFragment.kt
> +        val aggregation: ScoreAggregation? = ScoreAggregation.SUM,
neither this

2020-12-02 20:23 UTC, anarchuser commented on sdk/src/framework/sc/shared/ScoreFragment.kt
> +        val name: String?,
ah yeah, I missed those
ed28e0e9

2020-12-11 13:45 UTC, xerus2000 approved these changes

2020-12-11 13:46 UTC, merged